Fix Traceback related to TypeError: tcsetattr
Fixing the following issue. The reason is still unknown.

Traceback (most recent call last):
  File "src/gitradar.py", line 297, in <module>
    main()
  File "src/gitradar.py", line 278, in main
    screen.tty_signal_keys(undef)
  File "/tools/gitradar/venv/lib/python3.8/site-packages/urwid-2.1.1-py3.8-linux-x86_64.egg/urwid/display_common.py", line 776, in tty_signal_keys
    termios.tcsetattr(fileno, termios.TCSADRAIN, tattr)
TypeError: tcsetattr: elements of attributes must be characters or integers